services:
  dmarc-report:
    image: "gutmensch/dmarc-report:latest"
    hostname: dmarc-report
    container_name: dmarc-report
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      - "REPORT_DB_TYPE=pgsql"
      - "REPORT_DB_PORT=5432"
      - "REPORT_DB_NAME=dmarc_report"
      - "REPORT_DB_USER=dmarc_report"
      - "REPORT_DB_PASS=${DMARC_DB_PASSWORD}"
      - "PARSER_IMAP_SERVER=${IMAP_SERVER}"
      - "PARSER_IMAP_PORT=${IMAP_PORT:-993}"
      - "PARSER_IMAP_USER=${DMARC_EMAIL}"
      - "PARSER_IMAP_PASS=${DMARC_PASSWORD}"
      - "PARSER_IMAP_READ_FOLDER=Inbox"
      - "PARSER_IMAP_MOVE_FOLDER=${IMAP_MOVE_FOLDER:-processed}"
      - "PARSER_IMAP_MOVE_FOLDER_ERR=${IMAP_MOVE_FOLDER_ERR:-error}"

  db:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=dmarc_report"
      - "POSTGRES_USER=dmarc_report"
      - "POSTGRES_PASSWORD=${DMARC_DB_PASSWORD}"
    volumes:
      - ./run/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dmarc_report"]
      interval: 10s
      timeout: 10s
      retries: 5